JevKrayPersonalSite/Controllers/AboutMeController.cs
using JevKrayPersonalSite.Models;
using JevKrayPersonalSite.Services.MailSender;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JevKrayPersonalSite.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly ILogger<AboutMeController> _logger;

        public AboutMeController(ILogger<AboutMeController> logger)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult AboutMe()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JevKrayPersonalSite/Controllers/ApiControllers/MailApiController.cs
using System.Threading.Tasks;
using JevKrayPersonalSite.Services.ServiceInterfaces;
using JevKrayPersonalSite.PrivateServices.MailSender;
using Microsoft.AspNetCore.Mvc;

namespace JevKrayPersonalSite.Controllers.ApiControllers
{
    public class MailApiController : Controller
    {
        private readonly ICaptchaService _captchaService;

        public MailApiController(ICaptchaService captchaService)
        {
            _captchaService = captchaService;
        }

        [HttpPost]
        public async Task<IActionResult> MailSender(string Username, string Email, string Title, string Message, string Capcha)
        {
            if (!await _captchaService.CheckCaptchaAsync(Capcha))
            {
                return BadRequest("Invalid Captcha");
            }
            else
            {
                var mail = CodeMail.CreateMail(Username, Email, Title, Message);
                CodeMail.SendMail(mail);
                return Ok("Mail Sent");
            }
        }
    }
}

JevKrayPersonalSite/Controllers/UpdatesController.cs
using JevKrayPersonalSite.DAL;
using JevKrayPersonalSite.Models;
using JevKrayPersonalSite.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Text;

namespace JevKrayPersonalSite.Controllers
{
    public class UpdatesController : Controller
    {
        private const int pageSize = 10;

        private readonly ILogger<UpdatesController> _logger;
        private readonly JevkSiteDbContext _dbContext;

        public UpdatesController(JevkSiteDbContext dbContext, ILogger<UpdatesController> logger)
        {
            _dbContext = dbContext;
            _logger = logger;
        }

        public async Task<IActionResult> Updates(int page = 1)
        {
            var totalCount = await _dbContext.Commits.CountAsync();
            var commits = await _dbContext.Commits
                .OrderByDescending(c => c.Date)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            var viewModel = new UpdatesViewModel
            {
                Commits = commits,
                TotalCount = totalCount,
                PageSize = pageSize,
                CurrentPage = page
            };

            return View(viewModel);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JevKrayPersonalSite/Views/SharedNew/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" cntent="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href ="~/pictures/Icon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JevKrayPersonalSite.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
</head>
<body class="blackback">
    <header>
        <div class="header-1 dflex">
            <div class>
                <a class="a-brand-link dflex" asp-controller="AboutMe" asp-action="AboutMe">Eugene.</a>
            </div>
            <div class="header-left dflex dflex_link pt03">
                @{
                    if (ViewData["Title"] == "Education")
                    {
                        <a style="color: rgba(0,151,178,0.9);" class="a-link" asp-controller="Home" asp-action="Education">Education</a>
                    }
                    else
                    {
                        <a class="a-link" asp-controller="Home" asp-action="Education">Education</a>
                    }
                }
                @{
                    if (ViewData["Title"] == "Skills")
                    {
                        <a style="color: rgba(0,151,178,0.9);" class="a-link" asp-controller="Home" asp-action="Skills">Skills</a>
                    }
                    else
                    {
                        <a class="a-link" asp-controller="Home" asp-action="Skills">Skills</a>
                    }
                }
                @{
                    if (ViewData["Title"] == "Projects")
                    {
                        <a style="color: rgba(0,151,178,0.9);" class="a-link" asp-controller="Projects" asp-action="">Projects</a>
                    }
                    else
                    {
                        <a class="a-link" asp-controller="Projects" asp-action="">Projects</a>
                    }
                }
                @{
                    if (ViewData["Title"] == "Info")
                    {
                        <a style="color: rgba(0,151,178,0.9);" class="a-link" asp-controller="Home" asp-action="Info">Info</a>
                    }
                    else
                    {
                        <a class="a-link" asp-controller="Home" asp-action="Info">Info</a>
                    }
                }
            </div>
        </div>

            <div class="notification-header-message" id="notification-header-message">
                <p class="notification-text">
                    <span class="bold">Notification: </span>мобильная версия сайта находится в разработке, чтобы посмотреть прогресс перейдите во вкладку 
                    <a class="updates-in-notification" asp-controller="Updates" asp-action=""> Updates</a>
                </p>
                <div class="button-right">
                    <button id="closeBtn" class="btn-close"></button>
                </div>
        </div>

    </header>
    <div class="pb22 padding-12 container-wt-margin">
        <main role="main" class="remove-padding-down pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer remove-border footer-c1">
        <div class="container-wt-margin padding-l12-r18 remove-border footer-c2">
            <div class="footer-row">
                <div class="logos-am">
                    <div class="logo-item"> 
                        <a class="a-link-footer" href="https://t.me/eugenekray"><img src="~/pictures/tg.png" class="logo-img"> Telegram</a>
                    </div>
                    <div class="logo-item">
                        <a class="a-link-footer" href="https://github.com/Jevkray"><img src="~/pictures/git.png" class="logo-img"> GitHub</a>
                    </div>
                    <div class="logo-item">
                        <a class="a-link-footer" href="https://www.linkedin.com/in/eugene-krasovsky-164b60277/"><img src="~/pictures/linkedin.png" class="logo-img"> LinkedIn</a>
                    </div>
                    <div class="logo-item">
                        <a class="a-link-footer" data-bs-toggle="modal" data-bs-target="#exampleModal"><img src="~/pictures/gmail.png" class="logo-img"> Mail Me</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog madal-am-c2">
        <div class="modal-content">
            @using (Html.BeginForm("MailSender", "MailApi", FormMethod.Post, new { id = "mailSenderForm" }))
            {
                <div class="modal-header madal-h-am">
                    <h3 class="p-2 modal-title modal-title-am" id="exampleModalLabel">Send to Mail</h3>
                    <button type="button" class="btn-close margin-cross plr-3" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="font-1i3 modal-body madal-b-am">
                    <h3 class="p-3">В этом окне вы можете отправить сообщение мне на электронную почту</h3>
                    <div class="madal-b-name d-grid-am">
                        <input class="font-1i3 madal-b-name-text" type="text" name="Username" placeholder="Полное имя" />
                    </div>
                    <div class="madal-b-email d-grid-am">
                        <input class="font-1i3 madal-b-email-text" type="text" name="Email" placeholder="Электронная почта" />
                    </div>
                    <div class="madal-b-title d-grid-am">
                        <input class="font-1i3 madal-b-title-text" type="text" name="Title" placeholder="Тема сообщения" />
                    </div>
                    <div class="font-1i3 madal-b-message d-grid-am">
                        @Html.TextArea("Message", new { @class="madal-am-message madal-b-message-text", @placeholder="Текст сообщения" })
                    </div>
                </div>
                <div class="modal-footer madal-f-am">
                    <button type="button" class="madal-button-close btn btn-secondary madal-footer-width" data-bs-dismiss="modal">Закрыть</button>
                    <input type="button" class="madal-button-send btn btn-primary madal-footer-width" value="Отправить" onclick="sendMessage()" />
                </div>
            }
        </div>
    </div>
</div>

</html>

<script>
    function sendMessage() {

        event.preventDefault();

        var form = $('#mailSenderForm');
        var formData = form.serialize();

        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'), // Используем метод из атрибута формы
            data: formData,
            beforeSend: function () {
                // Show loading message before sending the request
                $('.modal-body').html('<h3 class="p-3">Loading...</h3>');
                $('.modal-footer').html('<button type="button" class="madal-button-close btn btn-secondary madal-footer-width" data-bs-dismiss="modal">Close</button>'); // Заменяем содержимое элемента с классом "modal-footer" на кнопку "Close"
            },
            success: function (response) {
                // Обработка успешного ответа от сервера
                console.log(response); // Выводим ответ в консоль
                $('.modal-body').html('<h3 class="p-3">Mail Sent, if you want to send more, update page</h3>'); // Заменяем содержимое элемента с классом "modal-body" на сообщение "Mail Sent..."
                $('.modal-footer').html('<button type="button" class="madal-button-close btn btn-secondary madal-footer-width" data-bs-dismiss="modal">Close</button>'); // Заменяем содержимое элемента с классом "modal-footer" на кнопку "Close"
            },  
            error: function (xhr, status, error) {
                // Обработка ошибки
                console.log(error); // Выводим ошибку в консоль
                // Дополнительный код для обработки ошибки
            }
        });
    }

    // Получение или установка значения куки
    function getCookie(name) {
        const value = "; " + document.cookie;
        const parts = value.split("; " + name + "=");
        if (parts.length === 2) return parts.pop().split(";").shift();
    }

    function setCookie(name, value, days) {
        const expires = new Date();
        expires.setTime(expires.getTime() + (48 * 60 * 60 * 1000)); // 48 часов
        document.cookie = `${name}=${value};expires=${expires.toUTCString()};path=/`;
    }

    document.addEventListener("DOMContentLoaded", function () {
        const notification = document.getElementById("notification-header-message");
        const closeBtn = document.getElementById("closeBtn");

        // Проверка куки и состояния уведомления
        const notificationClosed = getCookie("notificationClosed");
        if (notificationClosed === "true") {
            notification.style.display = "none";
        } else {
            notification.style.display = "flex";
        }

        // Обработчик для кнопки закрытия
        closeBtn.addEventListener("click", () => {
            notification.style.display = "none";
            setCookie("notificationClosed", "true", 30); // Сохраняем состояние в куки на 30 дней
        });
    });

</script>